### PR TITLE
Update pyxserver_wsgi.py

### PR DESCRIPTION
**Pull request by wwj718**
use results['msg'] to show message( if  correct)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @wwj718! I've created [OSPR-900](https://openedx.atlassian.net/browse/OSPR-900) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).
We can't start reviewing your pull request until you've   added yourself to the [AUTHORS](https://github.com/edx/xserver/blob/master/AUTHORS) file . Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by sarina** [comment]
@wwj718 Is this a change you meant to make on your own fork? I don't think this is going to be something we'll be merging into the edx upstream version of XServer - we use these messages to mean specific things, and changing this will break current courses.

**Comment by wwj718** [comment]
@sarina  Thank you for your reply.
I make a mistake when I read [XQueue worker interface](https://github.com/edx/xserver/blob/master/protocol.rst)
`{ "correct": true, "score": 1, "msg": "<p>Great! You got the right answer!</p>" }` is just a demo, but not interface

**Comment by sarina** [comment]
right, and the `results` response in that demo example contains the key `'correct'`, as this code expects.

**Comment by wwj718** [comment]
I got it ! Thanks : )

**Pull request closed without merging**
