### PR TITLE
Upgrade numpy to it's latest version

### PR DESCRIPTION
**Pull request by muzaffaryousaf**
We need to upgrade this to keep the numpy versions in-sync across different repos. 
Platform PR: https://github.com/edx/edx-platform/pull/12444

### CODE REVIEW

**Comment by muzaffaryousaf** [comment]
@andy-armstrong @nedbat PTAL. Thanks.

**Comment by muzaffaryousaf** [comment]
@andy-armstrong @nedbat Different version in xserver would't complaint about VersionConflict, Do you think we should update the numpy version here ?

**Comment by andy-armstrong** [comment]
@muzaffaryousaf I've never worked on XServer so I don't know. Your thinking sounds right to me though.  @feanil can you review this for @muzaffaryousaf?

**Comment by muzaffaryousaf** [comment]
@andy-armstrong I don't think that we need to update this for platform because this also uses different  environment.

**Comment by feanil** [comment]
@muzaffaryousaf @andy-armstrong the XServer runs very specific code for 6.002 courses.  That code may or may not work with new versions of Numpy. How was this change tested?

**Comment by muzaffaryousaf** [comment]
@feanil I've not tested this yet, due to think this is necessary to upgrade numpy here to avoid the VersionConflict errors ?

**Comment by muzaffaryousaf** [comment]
@feanil My understanding is Xserver runs as independent service instead of being installed as part of edx-platform. Is that true ?

**Comment by feanil** [comment]
I don't think you need to upgrade it here to avoid errors on the edx-platform side.  XServer is essentially on of our first IDAs so it's running on its own infrastructure.

**Comment by muzaffaryousaf** [comment]
Thanks. I'm closing this one.

**Pull request closed without merging**
